steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - goodreads-api
  - --entry-point=get-shelves
  - --trigger-http
  - --region=europe-west1
  - --source=.
  - --runtime=ruby26
  waitFor: ['-']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - goodreads-api-fetch-shelves
  - --entry-point=force-get-shelves
  - --trigger-topic=execute-fetch-shelves
  - --region=europe-west1
  - --source=.
  - --runtime=ruby26
  waitFor: ['-']